//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attent
    {
        public string log_id { get; set; }
        public string user_id { get; set; }
        public System.DateTime log_time { get; set; }
        public string device_id { get; set; }
        public byte log_type { get; set; }
        public string description { get; set; }
    }
}
